FROM debian:jessie-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV HOME /tmp

COPY _dist/linux-arm /

EXPOSE 44134

CMD ["/tiller"]
